ptitle = 'Roland SH-32';
pid = "c";
pnames = ['Patch','Rhythm Set'];
pdata = {};
pdata['Patch'] = [
  {id:"cC11",name:"Bass 1",num:"C11",cat:"Bank C"},
  {id:"cC12",name:"SyncLead 1",num:"C12",cat:"Bank C"},
  {id:"cC13",name:"Slicer 1",num:"C13",cat:"Bank C"},
  {id:"cC14",name:"Arpeggiator Saw 1",num:"C14",cat:"Bank C"},
  {id:"cC15",name:"Dist Lead",num:"C15",cat:"Bank C"},
  {id:"cC16",name:"LFO Pulsing",num:"C16",cat:"Bank C"},
  {id:"cC17",name:"Spank Noize",num:"C17",cat:"Bank C"},
  {id:"cC18",name:"GR300 Lead",num:"C18",cat:"Bank C"},
  {id:"cC21",name:"Synth Orch",num:"C21",cat:"Bank C"},
  {id:"cC22",name:"Techno Saws",num:"C22",cat:"Bank C"},
  {id:"cC23",name:"Ring Bell",num:"C23",cat:"Bank C"},
  {id:"cC24",name:"Filter Arpeggiator",num:"C24",cat:"Bank C"},
  {id:"cC25",name:"Noise Pad",num:"C25",cat:"Bank C"},
  {id:"cC26",name:"Low Sweep",num:"C26",cat:"Bank C"},
  {id:"cC27",name:"Bass Beat",num:"C27",cat:"Bank C"},
  {id:"cC28",name:"Arpeggiator Saw 2",num:"C28",cat:"Bank C"},
  {id:"cC31",name:"Moving Noise",num:"C31",cat:"Bank C"},
  {id:"cC32",name:"Moving Strings",num:"C32",cat:"Bank C"},
  {id:"cC33",name:"Soft Lead",num:"C33",cat:"Bank C"},
  {id:"cC34",name:"Arpeggiator Saw 3",num:"C34",cat:"Bank C"},
  {id:"cC35",name:"PWM Pad",num:"C35",cat:"Bank C"},
  {id:"cC36",name:"Techno Voice",num:"C36",cat:"Bank C"},
  {id:"cC37",name:"Analog E.Piano",num:"C37",cat:"Bank C"},
  {id:"cC38",name:"Zap",num:"C38",cat:"Bank C"},
  {id:"cC41",name:"Bass 2",num:"C41",cat:"Bank C"},
  {id:"cC42",name:"Bass 3",num:"C42",cat:"Bank C"},
  {id:"cC43",name:"Bass 4",num:"C43",cat:"Bank C"},
  {id:"cC44",name:"Bass 5",num:"C44",cat:"Bank C"},
  {id:"cC45",name:"Bass 6",num:"C45",cat:"Bank C"},
  {id:"cC46",name:"Bass 7",num:"C46",cat:"Bank C"},
  {id:"cC47",name:"Comp-F Bass",num:"C47",cat:"Bank C"},
  {id:"cC48",name:"Bass 8",num:"C48",cat:"Bank C"},
  {id:"cC51",name:"Bass 9",num:"C51",cat:"Bank C"},
  {id:"cC52",name:"Bass 10",num:"C52",cat:"Bank C"},
  {id:"cC53",name:"Bass 11",num:"C53",cat:"Bank C"},
  {id:"cC54",name:"Bass 12",num:"C54",cat:"Bank C"},
  {id:"cC55",name:"Bass 13",num:"C55",cat:"Bank C"},
  {id:"cC56",name:"Spank Bass",num:"C56",cat:"Bank C"},
  {id:"cC57",name:"Bass 14",num:"C57",cat:"Bank C"},
  {id:"cC58",name:"Lead 3",num:"C58",cat:"Bank C"},
  {id:"cC61",name:"Lead 4",num:"C61",cat:"Bank C"},
  {id:"cC62",name:"Lead 5",num:"C62",cat:"Bank C"},
  {id:"cC63",name:"Lead 6",num:"C63",cat:"Bank C"},
  {id:"cC64",name:"Lead 7",num:"C64",cat:"Bank C"},
  {id:"cC65",name:"Lead 8",num:"C65",cat:"Bank C"},
  {id:"cC66",name:"Lead 9",num:"C66",cat:"Bank C"},
  {id:"cC67",name:"Lead 10",num:"C67",cat:"Bank C"},
  {id:"cC68",name:"Lead 11",num:"C68",cat:"Bank C"},
  {id:"cC71",name:"Lead 12",num:"C71",cat:"Bank C"},
  {id:"cC72",name:"Lead 13",num:"C72",cat:"Bank C"},
  {id:"cC73",name:"Lead 14",num:"C73",cat:"Bank C"},
  {id:"cC74",name:"Lead 15",num:"C74",cat:"Bank C"},
  {id:"cC75",name:"Lead 16",num:"C75",cat:"Bank C"},
  {id:"cC76",name:"Syn Organ1",num:"C76",cat:"Bank C"},
  {id:"cC77",name:"Syn Organ2",num:"C77",cat:"Bank C"},
  {id:"cC78",name:"Synth Sitar",num:"C78",cat:"Bank C"},
  {id:"cC81",name:"Bell 1",num:"C81",cat:"Bank C"},
  {id:"cC82",name:"Bell 2",num:"C82",cat:"Bank C"},
  {id:"cC83",name:"Analog Piano 1",num:"C83",cat:"Bank C"},
  {id:"cC84",name:"Synth Clavi 1",num:"C84",cat:"Bank C"},
  {id:"cC85",name:"Synth Clani2",num:"C85",cat:"Bank C"},
  {id:"cC86",name:"Analog Key 1",num:"C86",cat:"Bank C"},
  {id:"cC87",name:"Analog Key 2",num:"C87",cat:"Bank C"},
  {id:"cC88",name:"SEQ1",num:"C88",cat:"Bank C"},
  {id:"cD11",name:"SEQ2",num:"D11",cat:"Bank D"},
  {id:"cD12",name:"SEQ3",num:"D12",cat:"Bank D"},
  {id:"cD13",name:"Reso BPF 1",num:"D13",cat:"Bank D"},
  {id:"cD14",name:"Reso BPF 2",num:"D14",cat:"Bank D"},
  {id:"cD15",name:"Reso HPF",num:"D15",cat:"Bank D"},
  {id:"cD16",name:"LoFiRing",num:"D16",cat:"Bank D"},
  {id:"cD17",name:"4th Saws",num:"D17",cat:"Bank D"},
  {id:"cD18",name:"Comp-F Lead",num:"D18",cat:"Bank D"},
  {id:"cD21",name:"4th Reso Saw",num:"D21",cat:"Bank D"},
  {id:"cD22",name:"SEQ 4",num:"D22",cat:"Bank D"},
  {id:"cD23",name:"SEQ 5",num:"D23",cat:"Bank D"},
  {id:"cD24",name:"PolySynth 1",num:"D24",cat:"Bank D"},
  {id:"cD25",name:"PolySynth 2",num:"D25",cat:"Bank D"},
  {id:"cD26",name:"PolySynth 3",num:"D26",cat:"Bank D"},
  {id:"cD27",name:"PolySynth 4",num:"D27",cat:"Bank D"},
  {id:"cD28",name:"Comp-F Poly",num:"D28",cat:"Bank D"},
  {id:"cD31",name:"TRAVELER 1",num:"D31",cat:"Bank D"},
  {id:"cD32",name:"SawStack 1",num:"D32",cat:"Bank D"},
  {id:"cD33",name:"SawStack 2",num:"D33",cat:"Bank D"},
  {id:"cD34",name:"SawStack 3",num:"D34",cat:"Bank D"},
  {id:"cD35",name:"Brass 1",num:"D35",cat:"Bank D"},
  {id:"cD36",name:"Brass 2",num:"D36",cat:"Bank D"},
  {id:"cD37",name:"Brass 3",num:"D37",cat:"Bank D"},
  {id:"cD38",name:"SynthPad 1",num:"D38",cat:"Bank D"},
  {id:"cD41",name:"SynthPad 2",num:"D41",cat:"Bank D"},
  {id:"cD42",name:"SynthPad 3",num:"D42",cat:"Bank D"},
  {id:"cD43",name:"SynthPad 4",num:"D43",cat:"Bank D"},
  {id:"cD44",name:"SynthPad 5",num:"D44",cat:"Bank D"},
  {id:"cD45",name:"Analog Strings",num:"D45",cat:"Bank D"},
  {id:"cD46",name:"Soft Strings",num:"D46",cat:"Bank D"},
  {id:"cD47",name:"Oct Strings",num:"D47",cat:"Bank D"},
  {id:"cD48",name:"SynthPad 6",num:"D48",cat:"Bank D"},
  {id:"cD51",name:"SynthPad 7",num:"D51",cat:"Bank D"},
  {id:"cD52",name:"SynthPad 8",num:"D52",cat:"Bank D"},
  {id:"cD53",name:"SynthPad 9",num:"D53",cat:"Bank D"},
  {id:"cD54",name:"Slicer 2",num:"D54",cat:"Bank D"},
  {id:"cD55",name:"LFOPad",num:"D55",cat:"Bank D"},
  {id:"cD56",name:"StepFlanger 1",num:"D56",cat:"Bank D"},
  {id:"cD57",name:"StepFlanger 2",num:"D57",cat:"Bank D"},
  {id:"cD58",name:"Pot",num:"D58",cat:"Bank D"},
  {id:"cD61",name:"MetalStick",num:"D61",cat:"Bank D"},
  {id:"cD62",name:"Electronica 1",num:"D62",cat:"Bank D"},
  {id:"cD63",name:"Arpeggiator Saw 3",num:"D63",cat:"Bank D"},
  {id:"cD64",name:"SynthFX 1",num:"D64",cat:"Bank D"},
  {id:"cD65",name:"SynthFX 2",num:"D65",cat:"Bank D"},
  {id:"cD66",name:"SynthFX 3",num:"D66",cat:"Bank D"},
  {id:"cD67",name:"SynthFX 4",num:"D67",cat:"Bank D"},
  {id:"cD68",name:"SynthFX 5",num:"D68",cat:"Bank D"},
  {id:"cD71",name:"SynthFX 6",num:"D71",cat:"Bank D"},
  {id:"cD72",name:"SynthFX 7",num:"D72",cat:"Bank D"},
  {id:"cD73",name:"SynthFX 8",num:"D73",cat:"Bank D"},
  {id:"cD74",name:"SynthFX 9",num:"D74",cat:"Bank D"},
  {id:"cD75",name:"SynthFX 10",num:"D75",cat:"Bank D"},
  {id:"cD76",name:"SynthFX 11",num:"D76",cat:"Bank D"},
  {id:"cD77",name:"SynthFX 12",num:"D77",cat:"Bank D"},
  {id:"cD78",name:"SweepingUp",num:"D78",cat:"Bank D"},
  {id:"cD81",name:"TRAVELER 2",num:"D81",cat:"Bank D"},
  {id:"cD82",name:"TRAVELER 3",num:"D82",cat:"Bank D"},
  {id:"cD83",name:"TRAVELER 4",num:"D83",cat:"Bank D"},
  {id:"cD84",name:"TRAVELER 5",num:"D84",cat:"Bank D"},
  {id:"cD85",name:"TRAVELER 6",num:"D85",cat:"Bank D"},
  {id:"cD86",name:"TRAVELER 7",num:"D86",cat:"Bank D"},
  {id:"cD87",name:"TRAVELER Bs",num:"D87",cat:"Bank D"},
  {id:"cD88",name:"INIT PATCH",num:"D88",cat:"Bank D"}, 
];

pdata['Rhythm Set'] = [
  {id:"cR1U",name:"r1U",num:"r1U",cat:"Bank R"}, 
  {id:"cR2U",name:"r2U",num:"r2U",cat:"Bank R"}, 
  {id:"cR3P",name:"r3P",num:"r3P",cat:"Bank R"}, 
  {id:"cR4P",name:"r4P",num:"r4P",cat:"Bank R"}, 
];
