export const presetTitle = 'Novation MiniNova';
export const presetNames = ['Preset'];
export const preset = {};
preset['Preset'] = [
  {id:"bA000",name:"BassIsWet DC",num:"A000",cat:"BASS"},
  {id:"bA001",name:"WobblyDub PM",num:"A001",cat:"BASS"},
  {id:"bA002",name:"OxyStrings DF",num:"A002",cat:"PAD/STRINGS"},
  {id:"bA003",name:"ModularClocks",num:"A003",cat:"ARP/MOVEMENT"},
  {id:"bA004",name:"ModWheelSync PM",num:"A004",cat:"KEYBOARD/LEAD"},
  {id:"bA005",name:"TB Mainiac PM",num:"A005",cat:"ARP/MOVEMENT"},
  {id:"bA006",name:"SurfinDaVortexPM",num:"A006",cat:"ARP/MOVEMENT"},
  {id:"bA007",name:"WobbleVocoder",num:"A007",cat:"VOCODER/VOCALTUNE"},
  {id:"bA008",name:"DrippyBass DF",num:"A008",cat:"BASS"},
  {id:"bA009",name:"Shufflin DF",num:"A009",cat:"ARP/MOVEMENT"},
  {id:"bA010",name:"SonarPing DF",num:"A010",cat:"PAD/STRINGS"},
  {id:"bA011",name:"Mr.E Pad DF",num:"A011",cat:"PAD/STRINGS"},
  {id:"bA012",name:"Nauseum DF",num:"A012",cat:"KEYBOARD/LEAD"},
  {id:"bA013",name:"ChubbyBass DF",num:"A013",cat:"BASS"},
  {id:"bA014",name:"Cry4Moon DF",num:"A014",cat:"KEYBOARD/LEAD"},
  {id:"bA015",name:"SnarkyLeadDF",num:"A015",cat:"-"},
  {id:"bA016",name:"NotSubtle DF",num:"A016",cat:"BASS"},
  {id:"bA017",name:"SygnWave DF",num:"A017",cat:"-"},
  {id:"bA018",name:"CubedBass DF",num:"A018",cat:"BASS"},
  {id:"bA019",name:"FurryBassDF",num:"A019",cat:"BASS"},
  {id:"bA020",name:"GallopString DF",num:"A020",cat:"ARP/MOVEMENT"},
  {id:"bA021",name:"Tinklers DF",num:"A021",cat:"PAD/STRINGS"},
  {id:"bA022",name:"Clusters DF",num:"A022",cat:"-"},
  {id:"bA023",name:"Majestic DF",num:"A023",cat:"PAD/STRINGS"},
  {id:"bA024",name:"AntsyBass DF",num:"A024",cat:"BASS"},
  {id:"bA025",name:"WowsieDF",num:"A025",cat:"ARP/MOVEMENT"},
  {id:"bA026",name:"FatBstrd DF",num:"A026",cat:"BASS"},
  {id:"bA027",name:"4ThCity DF",num:"A027",cat:"KEYBOARD/LEAD"},
  {id:"bA028",name:"Flanja DF",num:"A028",cat:"PAD/STRINGS"},
  {id:"bA029",name:"AcidicBass DF",num:"A029",cat:"BASS"},
  {id:"bA030",name:"ShapeShift DF",num:"A030",cat:"ARP/MOVEMENT"},
  {id:"bA031",name:"80'sSequencer",num:"A031",cat:"ARP/MOVEMENT"},
  {id:"bA032",name:"ToBeOver",num:"A032",cat:"KEYBOARD/LEAD"},
  {id:"bA033",name:"PunchyBass",num:"A033",cat:"BASS"},
  {id:"bA034",name:"MogueLead Mw S&H",num:"A034",cat:"KEYBOARD/LEAD"},
  {id:"bA035",name:"UpTheMwhl",num:"A035",cat:"ARP/MOVEMENT"},
  {id:"bA036",name:"MwhlFeedbacker",num:"A036",cat:"-"},
  {id:"bA037",name:"RosinBow",num:"A037",cat:"PAD/STRINGS"},
  {id:"bA038",name:"Viola",num:"A038",cat:"PAD/STRINGS"},
  {id:"bA039",name:"ArpStrings",num:"A039",cat:"PAD/STRINGS"},
  {id:"bA040",name:"Eurozone",num:"A040",cat:"ARP/MOVEMENT"},
  {id:"bA041",name:"MwhlSweeper",num:"A041",cat:"-"},
  {id:"bA042",name:"ModularResobass",num:"A042",cat:"BASS"},
  {id:"bA043",name:"SynthFretless",num:"A043",cat:"BASS"},
  {id:"bA044",name:"Wave2Sequence",num:"A044",cat:"ARP/MOVEMENT"},
  {id:"bA045",name:"Hop1Lead",num:"A045",cat:"KEYBOARD/LEAD"},
  {id:"bA046",name:"Hop2Lead",num:"A046",cat:"KEYBOARD/LEAD"},
  {id:"bA047",name:"OctavesLead",num:"A047",cat:"KEYBOARD/LEAD"},
  {id:"bA048",name:"Pianistic",num:"A048",cat:"KEYBOARD/LEAD"},
  {id:"bA049",name:"SofteePiano",num:"A049",cat:"KEYBOARD/LEAD"},
  {id:"bA050",name:"Clav1",num:"A050",cat:"KEYBOARD/LEAD"},
  {id:"bA051",name:"Clav2",num:"A051",cat:"KEYBOARD/LEAD"},
  {id:"bA052",name:"Balladeer",num:"A052",cat:"KEYBOARD/LEAD"},
  {id:"bA053",name:"VelEvoPad",num:"A053",cat:"ARP/MOVEMENT"},
  {id:"bA054",name:"HarmonicPad",num:"A054",cat:"PAD/STRINGS"},
  {id:"bA055",name:"Wurlygig",num:"A055",cat:"KEYBOARD/LEAD"},
  {id:"bA056",name:"HybridE.Bass",num:"A056",cat:"BASS"},
  {id:"bA057",name:"Vibes",num:"A057",cat:"KEYBOARD/LEAD"},
  {id:"bA058",name:"StellarPad",num:"A058",cat:"PAD/STRINGS"},
  {id:"bA059",name:"ClassicHorn",num:"A059",cat:"-"},
  {id:"bA060",name:"PsuedoOrgan",num:"A060",cat:"KEYBOARD/LEAD"},
  {id:"bA061",name:"CathedalOrgan",num:"A061",cat:"KEYBOARD/LEAD"},
  {id:"bA062",name:"AncientBells",num:"A062",cat:"-"},
  {id:"bA063",name:"ArpProSoloist",num:"A063",cat:"KEYBOARD/LEAD"},
  {id:"bA064",name:"BoogieOnBass",num:"A064",cat:"BASS"},
  {id:"bA065",name:"InTheHopper",num:"A065",cat:"BASS"},
  {id:"bA066",name:"Novachord",num:"A066",cat:"KEYBOARD/LEAD"},
  {id:"bA067",name:"OldSchoolR&B",num:"A067",cat:"BASS"},
  {id:"bA068",name:"TineE.Piano",num:"A068",cat:"KEYBOARD/LEAD"},
  {id:"bA069",name:"AlaskaSplitLoC",num:"A069",cat:"-"},
  {id:"bA070",name:"TaurusBass",num:"A070",cat:"BASS"},
  {id:"bA071",name:"LogDrumBass",num:"A071",cat:"BASS"},
  {id:"bA072",name:"Marimbish",num:"A072",cat:"KEYBOARD/LEAD"},
  {id:"bA073",name:"Kick&Bass",num:"A073",cat:"-"},
  {id:"bA074",name:"TunedNoise",num:"A074",cat:"-"},
  {id:"bA075",name:"PleaseDon'tStop",num:"A075",cat:"BASS"},
  {id:"bA076",name:"PoserBass",num:"A076",cat:"BASS"},
  {id:"bA077",name:"EasternStringer",num:"A077",cat:"-"},
  {id:"bA078",name:"MwlDreamyPad",num:"A078",cat:"PAD/STRINGS"},
  {id:"bA079",name:"Percomatic",num:"A079",cat:"ARP/MOVEMENT"},
  {id:"bA080",name:"GeigerCount DF",num:"A080",cat:"ARP/MOVEMENT"},
  {id:"bA081",name:"Airhead",num:"A081",cat:"PAD/STRINGS"},
  {id:"bA082",name:"Sweeper",num:"A082",cat:"PAD/STRINGS"},
  {id:"bA083",name:"Metallo2 PS",num:"A083",cat:"BASS"},
  {id:"bA084",name:"Stabolicious PS",num:"A084",cat:"KEYBOARD/LEAD"},
  {id:"bA085",name:"BottomFeeder PS",num:"A085",cat:"-"},
  {id:"bA086",name:"DeathWobble PS",num:"A086",cat:"BASS"},
  {id:"bA087",name:"LogDrumBass PS",num:"A087",cat:"BASS"},
  {id:"bA088",name:"NevrNo1 PS",num:"A088",cat:"BASS"},
  {id:"bA089",name:"SounTrax PS",num:"A089",cat:"PAD/STRINGS"},
  {id:"bA090",name:"Black3MailBox PS",num:"A090",cat:"-"},
  {id:"bA091",name:"LectroLux1 PS",num:"A091",cat:"BASS"},
  {id:"bA092",name:"GrandFinale1 PS",num:"A092",cat:"PAD/STRINGS"},
  {id:"bA093",name:"OcatveMangle PS",num:"A093",cat:"ARP/MOVEMENT"},
  {id:"bA094",name:"NotJust1 PS",num:"A094",cat:"BASS"},
  {id:"bA095",name:"WrenchKiss PS",num:"A095",cat:"ARP/MOVEMENT"},
  {id:"bA096",name:"PsiClopian PS",num:"A096",cat:"ARP/MOVEMENT"},
  {id:"bA097",name:"ShaverLead PS",num:"A097",cat:"KEYBOARD/LEAD"},
  {id:"bA098",name:"Sparky PS",num:"A098",cat:"ARP/MOVEMENT"},
  {id:"bA099",name:"Rosin8r2 PS",num:"A099",cat:"PAD/STRINGS"},
  {id:"bA100",name:"SeriesTubes PS",num:"A100",cat:"KEYBOARD/LEAD"},
  {id:"bA101",name:"Torched PS",num:"A101",cat:"KEYBOARD/LEAD"},
  {id:"bA102",name:"SwellPadN PS",num:"A102",cat:"PAD/STRINGS"},
  {id:"bA103",name:"Synchromatic1 PS",num:"A103",cat:"ARP/MOVEMENT"},
  {id:"bA104",name:"SprayBells PS",num:"A104",cat:"-"},
  {id:"bA105",name:"WormLead PS",num:"A105",cat:"KEYBOARD/LEAD"},
  {id:"bA106",name:"HugeManna PS",num:"A106",cat:"PAD/STRINGS"},
  {id:"bA107",name:"Mechano1 PS",num:"A107",cat:"BASS"},
  {id:"bA108",name:"Col.BatGuano PS",num:"A108",cat:"ARP/MOVEMENT"},
  {id:"bA109",name:"SpaceOboes PS",num:"A109",cat:"PAD/STRINGS"},
  {id:"bA110",name:"ThaSkinny PS",num:"A110",cat:"ARP/MOVEMENT"},
  {id:"bA111",name:"CylleString PS",num:"A111",cat:"PAD/STRINGS"},
  {id:"bA112",name:"Yuyuyu PS",num:"A112",cat:"BASS"},
  {id:"bA113",name:"Mudflaps PS",num:"A113",cat:"BASS"},
  {id:"bA114",name:"Churn PS",num:"A114",cat:"BASS"},
  {id:"bA115",name:"VoiceOfGrey PS",num:"A115",cat:"PAD/STRINGS"},
  {id:"bA116",name:"TwinPeaks PS",num:"A116",cat:"BASS"},
  {id:"bA117",name:"Gojira Breth PS",num:"A117",cat:"BASS"},
  {id:"bA118",name:"FreeClimber PS",num:"A118",cat:"ARP/MOVEMENT"},
  {id:"bA119",name:"CowFrog PS",num:"A119",cat:"BASS"},
  {id:"bA120",name:"TotoMundi PS",num:"A120",cat:"BASS"},
  {id:"bA121",name:"MotorOyl PS",num:"A121",cat:"BASS"},
  {id:"bA122",name:"StringTheory PS",num:"A122",cat:"PAD/STRINGS"},
  {id:"bA123",name:"BassHoovr PS",num:"A123",cat:"BASS"},
  {id:"bA124",name:"DubMonica PS",num:"A124",cat:"PAD/STRINGS"},
  {id:"bA125",name:"Black2Mailbox PS",num:"A125",cat:"PAD/STRINGS"},
  {id:"bA126",name:"Spelunkatron PS",num:"A126",cat:"BASS"},
  {id:"bA127",name:"JetPad PS",num:"A127",cat:"PAD/STRINGS"},
  {id:"bB000",name:"DiveBomb PS",num:"B000",cat:"-"},
  {id:"bB001",name:"FlyBy PS",num:"B001",cat:"-"},
  {id:"bB002",name:"FritzTropolis PS",num:"B002",cat:"-"},
  {id:"bB003",name:"MetalMotion PS",num:"B003",cat:"ARP/MOVEMENT"},
  {id:"bB004",name:"LectroPerx PS",num:"B004",cat:"-"},
  {id:"bB005",name:"ProggyBrkDwn PS",num:"B005",cat:"PAD/STRINGS"},
  {id:"bB006",name:"Sleet PS",num:"B006",cat:"ARP/MOVEMENT"},
  {id:"bB007",name:"OhYeah? PM",num:"B007",cat:"ARP/MOVEMENT"},
  {id:"bB008",name:"BreakdownArp PM",num:"B008",cat:"ARP/MOVEMENT"},
  {id:"bB009",name:"OowHopStab PM",num:"B009",cat:"-"},
  {id:"bB010",name:"HardDubBass PM",num:"B010",cat:"BASS"},
  {id:"bB011",name:"HardKnocks PM",num:"B011",cat:"KEYBOARD/LEAD"},
  {id:"bB012",name:"SpeakinModWBass PM",num:"B012",cat:"BASS"},
  {id:"bB013",name:"DubBass1 PM",num:"B013",cat:"BASS"},
  {id:"bB014",name:"SpaceBleep PM",num:"B014",cat:"-"},
  {id:"bB015",name:"HipHopStab1 PM",num:"B015",cat:"-"},
  {id:"bB016",name:"PinPrick PM",num:"B016",cat:"-"},
  {id:"bB017",name:"FloatinNuttelaPM",num:"B017",cat:"-"},
  {id:"bB018",name:"Pizz-a-Cake PM",num:"B018",cat:"PAD/STRINGS"},
  {id:"bB019",name:"WildStabba PM",num:"B019",cat:"-"},
  {id:"bB020",name:"R&B Bass PM",num:"B020",cat:"BASS"},
  {id:"bB021",name:"GrowLie Dub PM",num:"B021",cat:"BASS"},
  {id:"bB022",name:"PitcHie Dub PM",num:"B022",cat:"BASS"},
  {id:"bB023",name:"Talkie Dub PM",num:"B023",cat:"BASS"},
  {id:"bB024",name:"FarTie Dub PM",num:"B024",cat:"-"},
  {id:"bB025",name:"PitchPad PM",num:"B025",cat:"PAD/STRINGS"},
  {id:"bB026",name:"SQ PotLid PM",num:"B026",cat:"KEYBOARD/LEAD"},
  {id:"bB027",name:"Padulushious PM",num:"B027",cat:"PAD/STRINGS"},
  {id:"bB028",name:"LuxuryPad DF",num:"B028",cat:"PAD/STRINGS"},
  {id:"bB029",name:"TranceAttack PM",num:"B029",cat:"ARP/MOVEMENT"},
  {id:"bB030",name:"1Hi1Lo DF",num:"B030",cat:"-"},
  {id:"bB031",name:"ThroatyDub PM",num:"B031",cat:"BASS"},
  {id:"bB032",name:"AngryDub PM",num:"B032",cat:"BASS"},
  {id:"bB033",name:"PercussiveDub PM",num:"B033",cat:"BASS"},
  {id:"bB034",name:"SlideyDub PM",num:"B034",cat:"BASS"},
  {id:"bB035",name:"BigFoot DF",num:"B035",cat:"ARP/MOVEMENT"},
  {id:"bB036",name:"WobblyScratch PM",num:"B036",cat:"BASS"},
  {id:"bB037",name:"PitchieStabba PM",num:"B037",cat:"-"},
  {id:"bB038",name:"NoiseyPicker PM",num:"B038",cat:"-"},
  {id:"bB039",name:"HypaSquare PM",num:"B039",cat:"KEYBOARD/LEAD"},
  {id:"bB040",name:"HypaMeltDownz PM",num:"B040",cat:"-"},
  {id:"bB041",name:"TalkinNonsencePM",num:"B041",cat:"BASS"},
  {id:"bB042",name:"WaveSequence PM",num:"B042",cat:"ARP/MOVEMENT"},
  {id:"bB043",name:"CallinLondon PM",num:"B043",cat:"BASS"},
  {id:"bB044",name:"FM SyncLeadMW PM",num:"B044",cat:"KEYBOARD/LEAD"},
  {id:"bB045",name:"ChatterArp PM",num:"B045",cat:"ARP/MOVEMENT"},
  {id:"bB046",name:"StabbaNaught PM",num:"B046",cat:"-"},
  {id:"bB047",name:"BreakdownPad PM",num:"B047",cat:"PAD/STRINGS"},
  {id:"bB048",name:"Niagra DF",num:"B048",cat:"-"},
  {id:"bB049",name:"OnYourBackBassPM",num:"B049",cat:"BASS"},
  {id:"bB050",name:"EssexSynth PM",num:"B050",cat:"-"},
  {id:"bB051",name:"InDaCrypt PM",num:"B051",cat:"-"},
  {id:"bB052",name:"DirtStabSplit PM",num:"B052",cat:"-"},
  {id:"bB053",name:"FingaPicka PM",num:"B053",cat:"ARP/MOVEMENT"},
  {id:"bB054",name:"BangaDrumBass PM",num:"B054",cat:"-"},
  {id:"bB055",name:"PowaChord PM",num:"B055",cat:"KEYBOARD/LEAD"},
  {id:"bB056",name:"OhhWhaarG PM",num:"B056",cat:"-"},
  {id:"bB057",name:"Electric Dyno PM",num:"B057",cat:"KEYBOARD/LEAD"},
  {id:"bB058",name:"BreathyVocoder",num:"B058",cat:"VOCODER/VOCALTUNE"},
  {id:"bB059",name:"LeadVocoder",num:"B059",cat:"VOCODER/VOCALTUNE"},
  {id:"bB060",name:"Pad1Vocoder",num:"B060",cat:"VOCODER/VOCALTUNE"},
  {id:"bB061",name:"Pad2Vocoder",num:"B061",cat:"VOCODER/VOCALTUNE"},
  {id:"bB062",name:"Pad3Vocoder",num:"B062",cat:"VOCODER/VOCALTUNE"},
  {id:"bB063",name:"Pad4Vocoder",num:"B063",cat:"VOCODER/VOCALTUNE"},
  {id:"bB064",name:"RobotVocoder",num:"B064",cat:"VOCODER/VOCALTUNE"},
  {id:"bB065",name:"KwerkyVocoder",num:"B065",cat:"VOCODER/VOCALTUNE"},
  {id:"bB066",name:"SkyBlueVocoder",num:"B066",cat:"VOCODER/VOCALTUNE"},
  {id:"bB067",name:"ClimbingVocoder",num:"B067",cat:"VOCODER/VOCALTUNE"},
  {id:"bB068",name:"TwistedVocoder",num:"B068",cat:"VOCODER/VOCALTUNE"},
  {id:"bB069",name:"MorphingVocoder",num:"B069",cat:"VOCODER/VOCALTUNE"},
  {id:"bB070",name:"EinsZwieVocoder",num:"B070",cat:"VOCODER/VOCALTUNE"},
  {id:"bB071",name:"BreakerVocoder",num:"B071",cat:"VOCODER/VOCALTUNE"},
  {id:"bB072",name:"LookNoFX DF",num:"B072",cat:"-"},
  {id:"bB073",name:"Aaah1",num:"B073",cat:"VOCODER/VOCALTUNE"},
  {id:"bB074",name:"Aaah2",num:"B074",cat:"VOCODER/VOCALTUNE"},
  {id:"bB075",name:"LvlupVocTune",num:"B075",cat:"VOCODER/VOCALTUNE"},
  {id:"bB076",name:"LvlDownVocTune",num:"B076",cat:"VOCODER/VOCALTUNE"},
  {id:"bB077",name:"NormVocTune",num:"B077",cat:"VOCODER/VOCALTUNE"},
  {id:"bB078",name:"PlaykeysVocTune",num:"B078",cat:"VOCODER/VOCALTUNE"},
  {id:"bB079",name:"UpAlwaysVocTune",num:"B079",cat:"VOCODER/VOCALTUNE"},
  {id:"bB080",name:"SciFiVocoder",num:"B080",cat:"VOCODER/VOCALTUNE"},
  {id:"bB081",name:"VocodSynthKeyz",num:"B081",cat:"VOCODER/VOCALTUNE"},
  {id:"bB082",name:"PlayScaleVocTune",num:"B082",cat:"VOCODER/VOCALTUNE"},
  {id:"bB083",name:"StopTapeVocTune",num:"B083",cat:"VOCODER/VOCALTUNE"},
  {id:"bB084",name:"FilteredVocTune",num:"B084",cat:"VOCODER/VOCALTUNE"},
  {id:"bB085",name:"SoloPitchVocTune",num:"B085",cat:"VOCODER/VOCALTUNE"},
  {id:"bB086",name:"RingmodVocTune",num:"B086",cat:"VOCODER/VOCALTUNE"},
  {id:"bB087",name:"Vocod&Tune",num:"B087",cat:"VOCODER/VOCALTUNE"},
  {id:"bB088",name:"LushVocoder",num:"B088",cat:"VOCODER/VOCALTUNE"},
  {id:"bB089",name:"DistVocTune",num:"B089",cat:"VOCODER/VOCALTUNE"},
  {id:"bB090",name:"MachineMenBass",num:"B090",cat:"BASS"},
  {id:"bB091",name:"SimpleRiff",num:"B091",cat:"-"},
  {id:"bB092",name:"LeagueBass",num:"B092",cat:"BASS"},
  {id:"bB093",name:"DigiMallot BC",num:"B093",cat:"ARP/MOVEMENT"},
  {id:"bB094",name:"LeadDub MW",num:"B094",cat:"KEYBOARD/LEAD"},
  {id:"bB095",name:"CleanDutch AL",num:"B095",cat:"KEYBOARD/LEAD"},
  {id:"bB096",name:"GettaBass AL",num:"B096",cat:"BASS"},
  {id:"bB097",name:"LilPopDaWorld AL",num:"B097",cat:"ARP/MOVEMENT"},
  {id:"bB098",name:"WibWob AL",num:"B098",cat:"BASS"},
  {id:"bB099",name:"Organic DC",num:"B099",cat:"KEYBOARD/LEAD"},
  {id:"bB100",name:"HartThrob DC",num:"B100",cat:"KEYBOARD/LEAD"},
  {id:"bB101",name:"Squelcher DC",num:"B101",cat:"BASS"},
  {id:"bB102",name:"FaeryCave DC",num:"B102",cat:"PAD/STRINGS"},
  {id:"bB103",name:"HateStrings DC",num:"B103",cat:"PAD/STRINGS"},
  {id:"bB104",name:"QuartetFaris DC",num:"B104",cat:"KEYBOARD/LEAD"},
  {id:"bB105",name:"PoppyRen DC",num:"B105",cat:"ARP/MOVEMENT"},
  {id:"bB106",name:"OneUgly... DC",num:"B106",cat:"KEYBOARD/LEAD"},
  {id:"bB107",name:"WobbaDrop DC",num:"B107",cat:"-"},
  {id:"bB108",name:"JahJahJah DC",num:"B108",cat:"BASS"},
  {id:"bB109",name:"JellyLead DC",num:"B109",cat:"KEYBOARD/LEAD"},
  {id:"bB110",name:"BitXBowl DC",num:"B110",cat:"-"},
  {id:"bB111",name:"42Deep DF",num:"B111",cat:"KEYBOARD/LEAD"},
  {id:"bB112",name:"TearsInRain DC",num:"B112",cat:"PAD/STRINGS"},
  {id:"bB113",name:"CreepyDrone DP",num:"B113",cat:"PAD/STRINGS"},
  {id:"bB114",name:"JonnaBells",num:"B114",cat:"-"},
  {id:"bB115",name:"Ark EP",num:"B115",cat:"KEYBOARD/LEAD"},
  {id:"bB116",name:"SolidKick OB",num:"B116",cat:"-"},
  {id:"bB117",name:"JumpIt!",num:"B117",cat:"-"},
  {id:"bB118",name:"FairlyLite",num:"B118",cat:"-"},
  {id:"bB119",name:"SpaceVoyageTC3",num:"B119",cat:"ARP/MOVEMENT"},
  {id:"bB120",name:"SwellSaw",num:"B120",cat:"-"},
  {id:"bB121",name:"AmazonNatives",num:"B121",cat:"-"},
  {id:"bB122",name:"PotsAndPans",num:"B122",cat:"-"},
  {id:"bB123",name:"RandomRepSnare",num:"B123",cat:"-"},
  {id:"bB124",name:"KarlosWhey",num:"B124",cat:"-"},
  {id:"bB125",name:"SynthPopPiano",num:"B125",cat:"-"},
  {id:"bB126",name:"PinCode",num:"B126",cat:"ARP/MOVEMENT"},
  {id:"bB127",name:"CoatHanger JF",num:"B127",cat:"ARP/MOVEMENT"},
    ];
